spring:  
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application: 
    name: microservicecloud-config-xufengpeng-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-xufengpeng-test    